src/apps/service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    # Operator Category
    path('operator/category/add', views.OperatorCategoryAddView.as_view(), name='operator_category__add'),
    path('operator/category/list', views.OperatorCategoryListView.as_view(), name='operator_category__list'),
    path('operator/category/delete/<int:category_id>', views.OperatorCategoryDeleteView.as_view(),
         name='operator_category__delete'),
    path('operator/category/detail/<int:category_id>', views.OperatorCategoryDetailView.as_view(),
         name='operator_category__detail'),
    # Operator
    path('operator/add', views.OperatorAddView.as_view(), name='operator__add'),
    path('operator/delete/<int:operator_id>', views.OperatorDeleteView.as_view(), name='operator__delete'),
    path('operator/detail/<int:operator_id>', views.OperatorDetailView.as_view(), name='operator__detail'),
    # Operator WorkSample
    path('operator/worksample/add', views.OperatorWorkSampleAddView.as_view(), name='operator_worksample__add'),
    path('operator/worksample/delete/<int:work_sample_id>', views.OperatorWorkSampleDeleteView.as_view(),
         name='operator_worksample__delete'),
    # Operator Reserve Time
    path('operator/detail/<int:operator_id>/reserve/add', views.OperatorReserveAddView.as_view(),
         name='operator_reserve__add'),
    path('operator/reserve/list', views.OperatorReserveListView.as_view(),
         name='operator_reserve__list'),
]

src/config/urls.py
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls', namespace='public')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('service/', include('apps.service.urls', namespace='service')),
    path('shop/', include('apps.shop.urls', namespace='shop')),
    path('program/', include('apps.program.urls', namespace='program')),
    path('operation/', include('apps.operation.urls', namespace='operation')),
    path('communication/', include('apps.communication.urls', namespace='communication')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler403 = 'apps.public.views.err_403_handler'
# handler404 = 'apps.public.views.err_404_handler'
# handler500 = 'apps.public.views.err_500_handler'


# Rename site header & title & index_title
admin.site.site_header = _("Site Management")
admin.site.index_title = _("Management Panel")
admin.site.site_title = _("Vala Clinic")

src/apps/service/models.py
from django.utils.translation import gettext as _
from django.shortcuts import reverse
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField
from apps.core.models import BaseModel


class OperatorCategory(BaseModel):
    """
        TODO: It is better to use the 'User' class in the future
    """
    name = models.CharField(_('Name'), max_length=100)

    class Meta:
        verbose_name = _('Operator category')
        verbose_name_plural = _('Operator categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('service:operator_category__detail', args=(self.id,))

    def get_operators(self):
        return self.operator_set.all()


class Operator(BaseModel):
    name = models.CharField(_('Name'), max_length=100)
    picture = models.ImageField(_('Picture'), upload_to='images/services/operators/pictures/')
    category = models.ForeignKey(OperatorCategory, verbose_name=_('Category'), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Operator')
        verbose_name_plural = _('Operators')
        ordering = ('-id',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('service:operator__detail', args=(self.id,))

    def get_work_samples(self):
        return self.operatorworksample_set.all()


class OperatorWorkSample(BaseModel):
    operator = models.ForeignKey(Operator, verbose_name=_('Operator'), on_delete=models.CASCADE)
    title = models.CharField(_('Title'), max_length=100)
    image = models.ImageField(_('Image'), upload_to='images/services/operators/work_samples/')
    description = models.TextField(_('Description'), null=True)

    class Meta:
        verbose_name = _('Operator work sample')
        verbose_name_plural = _('Operator work samples')

    def __str__(self):
        return f'{self.operator} - {self.title[:30]}'


class OperatorReserve(BaseModel):
    operator = models.ForeignKey(Operator, verbose_name=_('Operator'), on_delete=models.CASCADE)
    phonenumber = PhoneNumberField(_('Phone number'), max_length=32)
    description = models.TextField(_('Description'), null=True)

    class Meta:
        verbose_name = _('Operator reserve')
        verbose_name_plural = _('Operator reserves')
        ordering = ('-id',)

    def __str__(self):
        return f'#{self.id} Reserve - {self.operator}'

    def get_raw_phonenumber(self):
        p = str(self.phonenumber).replace('+98', '')
        return p

src/apps/service/forms.py
from django.forms import ModelForm
from . import models


class OperatorCategoryAdd(ModelForm):
    class Meta:
        model = models.OperatorCategory
        fields = '__all__'


class OperatorAdd(ModelForm):
    class Meta:
        model = models.Operator
        fields = '__all__'


class OperatorWorkSampleAdd(ModelForm):
    class Meta:
        model = models.OperatorWorkSample
        fields = '__all__'


class OperatorReserveAdd(ModelForm):
    class Meta:
        model = models.OperatorReserve
        fields = '__all__'

src/apps/service/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext as _
from django.views.generic import TemplateView, ListView, View
from apps.account.mixins import AccessRequiredMixin
from apps.account.enums import UserAccessEnum
from apps.core.utils import validate_form
from django.contrib import messages
from . import models
from . import forms


class OperatorCategoryListView(ListView):
    template_name = 'service/operator/category/list.html'
    model = models.OperatorCategory
    context_object_name = 'categories'


class OperatorCategoryDetailView(View):

    def get(self, request, category_id):
        context = {
            'category': get_object_or_404(models.OperatorCategory, id=category_id)
        }
        return render(request, 'service/operator/category/detail.html', context)


class OperatorCategoryAddView(AccessRequiredMixin, View):
    roles = [UserAccessEnum.ADMIN]

    def post(self, request):
        data = request.POST

        form = forms.OperatorCategoryAdd(data)
        if validate_form(request, form) is False:
            return redirect('service:operator_category__list')
        category = form.save()

        messages.success(request, _('Category Created Successfully'))
        return redirect('service:operator_category__list')


class OperatorCategoryDeleteView(AccessRequiredMixin, View):
    roles = [UserAccessEnum.ADMIN]

    def post(self, request, category_id=0):
        """ if category_id is 0 then get category in request data """
        data = request.POST

        category_id = category_id or data.get('category', 0)
        category = get_object_or_404(models.OperatorCategory, id=category_id)
        category.delete()

        messages.success(request, _('Category Deleted Successfully'))
        return redirect('service:operator_category__list')


class OperatorAddView(View):

    def post(self, request):
        referer_url = request.META.get('HTTP_REFERER')
        data = request.POST

        form = forms.OperatorAdd(data, files=request.FILES)
        if validate_form(request, form) is False:
            return redirect(referer_url)
        operator = form.save()

        messages.success(request, _('Operator Created Successfully'))
        return redirect(referer_url)


class OperatorDeleteView(AccessRequiredMixin, View):
    roles = [UserAccessEnum.ADMIN]

    def post(self, request, operator_id):
        referer_url = request.META.get('HTTP_REFERER')
        operator = get_object_or_404(models.Operator, id=operator_id)
        operator.delete()

        messages.success(request, _('Operator Deleted Successfully'))
        return redirect(referer_url)


class OperatorDetailView(TemplateView):
    template_name = 'service/operator/detail.html'

    def get_context_data(self, **kwargs):
        context = super(OperatorDetailView, self).get_context_data(**kwargs)
        operator_id = kwargs.get('operator_id')

        context.update({
            'operator': get_object_or_404(models.Operator, id=operator_id)
        })
        return context


class OperatorWorkSampleAddView(AccessRequiredMixin, TemplateView):
    roles = [UserAccessEnum.ADMIN]

    def post(self, request):
        referer_url = request.META.get('HTTP_REFERER')
        data = request.POST

        form = forms.OperatorWorkSampleAdd(data, files=request.FILES)
        if validate_form(request, form) is False:
            return redirect(referer_url)
        form.save()

        messages.success(request, _('Work Sample Created Successfully'))
        return redirect(referer_url)


class OperatorWorkSampleDeleteView(AccessRequiredMixin, View):
    roles = [UserAccessEnum.ADMIN]

    def get(self, request, work_sample_id):
        work_sample = get_object_or_404(models.OperatorWorkSample, id=work_sample_id)
        work_sample.delete()

        messages.success(request, _('Work Sample Deleted Successfully'))
        return redirect(work_sample.operator.get_absolute_url())


class OperatorReserveAddView(View):

    def post(self, request, operator_id):
        operator = get_object_or_404(models.Operator, id=operator_id)
        data = request.POST.copy()

        # Set additional values
        data['operator'] = operator

        form = forms.OperatorReserveAdd(data)
        if validate_form(request, form) is False:
            return redirect(operator.get_absolute_url())
        form.save()

        messages.success(request, _('Operator Time Was Successfully Booked'))
        # TODO: send sms to admins
        ...
        return redirect(operator.get_absolute_url())


class OperatorReserveListView(AccessRequiredMixin, TemplateView):
    template_name = 'service/operator/reserve/list.html'
    roles = [UserAccessEnum.ADMIN]

    def get_context_data(self, **kwargs):
        context = super(OperatorReserveListView, self).get_context_data(**kwargs)

        context.update({
            'reserves': models.OperatorReserve.objects.all()
        })
        return context

src/apps/service/templates/service/operator/category/detail.html
{% extends 'base-template.html' %}
{% load static %}


{% block title %}والا | خدمات حضوری{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/khadamat-hozori.css' %}">
    <style>

    </style>
{% endblock %}

{% block body_class %}bg{% endblock %}

{% block content %}
    <!-- Include user/admin menus -->
    {% include 'menus.html' %}

    <div class="container-fluid col-md-11 pb-5">
        <main class="main">
            <div class="profile-user-category">
                <div class="inner-profile-user-category col-12">
                    <div class="logo">
                        <div class="col-7 col-md-4">
                            <img src="{% static 'images/vala-logo.png' %}" alt="Vala logo">
                        </div>
                    </div>
                    <div class="name">
                        {{ category.name }}
                    </div>
                    {% if request.user.has_admin_access %}
                        <div class="content-actions mt-5 mb-1 d-flex justify-content-between align-items-center col-12 col-md-5 mx-auto">
                            <div>
                                <h4>عملیات</h4>
                            </div>
                            <div>
                                <button class="btn btn-success" id="add-operator">
                                    افزودن اپراتور
                                </button>
                                <button class="btn btn-danger" id="delete-category">
                                    حذف دسته بندی
                                </button>
                            </div>
                        </div>
                    {% endif %}
                    <div class="profile-user-category mt-5">
                        <div class="inner-profile-user-category col-12 col-md-5">
                            <div class="contentfff">
                                <div class="user-category" id="container">
                                    {% for operator in category.get_operators %}
                                        <div class="col-12 p-2">
                                            <a href="{{ operator.get_absolute_url }}">
                                                <div class="item-user">
                                                    <div class="col-3 col-md-2">
                                                        <div class="image-user">
                                                            <img src="{{ operator.picture.url }}"
                                                                 alt="{{ operator.name }}">
                                                        </div>
                                                    </div>

                                                    <div class="col-9 col-md-10 nnn">
                                                        <div class="name-user">
                                                            {{ operator.name }}
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>

                                        </div>
                                        {% empty %}
                                        <div class="container-not-found-base p-4 fs-4">
                                            <p>اپراتوری یافت نشد</p>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    {% if request.user.has_admin_access %}

        <div class="content-modal add-operator-modal">
            <div class="inner-modal">
                <form method="POST" action="{% url 'service:operator__add' %}" enctype="multipart/form-data"
                      class="px-4 pt-2"
                      style="min-width: 300px;">
                    {% csrf_token %}
                    <div class="py-2 text-white">
                        <input type="hidden" name="category" value="{{ category.id }}">
                        <div class="title">
                            <h5>افزودن اپراتور</h5>
                            <div role="button" class="close-modal-add-post">
                                <img src="{% static 'images/icons/close-modal.png' %}" alt="Close button">
                            </div>
                        </div>
                        <label class="text-right justify-content-start w-100 mt-2">
                            نام و نام خانوادگی
                            <input type="text" name="name" placeholder="نام و نام خانوادگی"
                                   class="form-control bg-transparent text-white mt-1" required="">
                        </label>
                        <label class="text-right justify-content-start w-100 mt-2">
                            تصویر
                            <input type="file" accept="image/*" name="picture" placeholder="تصویر"
                                   class="form-control bg-transparent text-white mt-1" required="">
                        </label>
                    </div>
                    <div class="text-center mt-3" id="add-post">
                        <button type="submit" class="btn btn-success col-12">
                            ایجاد اپراتور
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="content-modal delete-category-modal">
            <div class="inner-modal">
                <form method="POST" action="{% url 'service:operator_category__delete' category_id=category.id %}"
                      class="px-4 pt-2"
                      style="min-width: 300px;">
                    {% csrf_token %}
                    <div class="py-2 text-white">
                        <div class="title">
                            <h5>حذف دسته بندی</h5>
                            <div role="button" class="close-modal-add-post">
                                <img src="{% static 'images/icons/close-modal.png' %}" alt="Close button">
                            </div>
                        </div>
                        <h4 class="text-danger mt-3">
                            توجه کنید با حذف دسته بندی تمامی اپراتور ها و محتوای مربوط به ان حذف خواهند شد ، دقت کنید
                        </h4>
                    </div>
                    <div class="text-center mt-3" id="add-post">
                        <button type="submit" class="btn btn-danger col-12">
                            متوجه ام ، حذف دسته بندی
                        </button>
                    </div>
                </form>
            </div>
        </div>

    {% endif %}

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menus.js' %}"></script>
    <script>
        // ----------------- Modal Category Add -----------------
        let btnsShowModal = document.querySelector("#add-operator");
        let btnsCloseModal = document.querySelector(".close-modal-add-post");
        let contentModals = document.querySelector(".add-operator-modal");

        btnsShowModal.addEventListener("click", () => {
            contentModals.classList.add("active");
        });

        btnsCloseModal.addEventListener("click", () => {
            contentModals.classList.remove("active");
        });
        contentModals.addEventListener("click", (e) => {
            if (e.target.className === "inner-modal")
                contentModals.classList.remove("active");
        });

        // ----------------- Modal Category Delete -----------------
        let btnsShowModal_b = document.querySelector("#delete-category");
        let btnsCloseModal_b = document.querySelector(".close-modal-add-post");
        let contentModals_b = document.querySelector(".delete-category-modal");

        btnsShowModal_b.addEventListener("click", () => {
            contentModals_b.classList.add("active");
        });

        btnsCloseModal_b.addEventListener("click", () => {
            contentModals_b.classList.remove("active");
        });
        contentModals_b.addEventListener("click", (e) => {
            if (e.target.className === "inner-modal")
                contentModals_b.classList.remove("active");
        });
    </script>
{% endblock %}

src/apps/service/templates/service/operator/category/list.html
{% extends 'base-template.html' %}
{% load static %}


{% block title %}والا | خدمات حضوری{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/khadamat-hozori.css' %}">
{% endblock %}

{% block body_class %}bg{% endblock %}

{% block content %}
    <!-- Include user/admin menus -->
    {% include 'menus.html' %}

    <div class="container-fluid col-md-11 pb-5">
        <main class="main">
            <div class="profile-user-category">
                <div class="inner-profile-user-category col-12 col-md-5">
                    <div class="logo">
                        <div class="col-7 col-md-4">
                            <img src="{% static 'images/vala-logo.png' %}" alt="Vala logo">
                        </div>
                    </div>
                    <div class="name">
                        خدمات حضوری
                    </div>
                    {% if request.user.has_admin_access %}
                        <div class="content-actions mt-4 mb-1 d-flex justify-content-between align-items-center">
                            <div>
                                <h4>عملیات</h4>
                            </div>
                            <div>
                                <button class="btn btn-success" id="add-category">
                                    افزودن دسته بندی
                                </button>
                                <button class="btn btn-danger" id="delete-category">
                                    حذف دسته بندی
                                </button>
                            </div>
                        </div>
                    {% endif %}
                    <section class="profile-category" id="container">
                        {% for category in categories %}
                            <div class="col-10 col-md-8 p-2">
                                <a href="{% url 'service:operator_category__detail' category_id=category.id %}">
                                    <div class="item-profile" id="blue">
                                        <div class="inner-item-hozori">
                                            {{ category.name }}
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% empty %}
                            <div class="container-not-found-base p-4 fs-4">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </section>
                </div>
            </div>
        </main>
    </div>

    {% if request.user.has_admin_access %}
        <div class="content-modal add-category-modal">
            <div class="inner-modal">
                <form method="POST" action="{% url 'service:operator_category__add' %}"
                      class="px-4 pt-2"
                      style="min-width: 300px;">
                    {% csrf_token %}
                    <div class="py-2 text-white">
                        <div class="title">
                            <h5>افزودن دسته بندی</h5>
                            <div role="button" class="close-modal-add-category">
                                <img src="{% static 'images/icons/close-modal.png' %}" alt="Close button">
                            </div>
                        </div>
                        <label class="text-right justify-content-start w-100 mt-2">
                            عنوان
                            <input type="text" name="name" placeholder="عنوان دسته بندی"
                                   class="form-control bg-transparent text-white mt-1" required="">
                        </label>
                    </div>
                    <div class="text-center mt-3" id="add-post">
                        <button type="submit" class="btn btn-success col-12">
                            ثبت
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="content-modal delete-category-modal">
            <div class="inner-modal">
                <form method="POST" action="{% url 'service:operator_category__delete' category_id=0 %}"
                      class="px-4 pt-2"
                      style="min-width: 300px;">
                    {% csrf_token %}
                    <div class="py-2 text-white">
                        <div class="title">
                            <h5>حذف دسته بندی</h5>
                            <div role="button" class="close-modal-delete-category">
                                <img src="{% static 'images/icons/close-modal.png' %}" alt="Close button">
                            </div>
                        </div>
                        <label class="text-right justify-content-start w-100 mt-2">
                            دسته بندی مورد نظر را انتخاب کنید
                            <select name="category" class="form-control" required>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </label>
                        <h4 class="text-danger mt-3">
                            توجه کنید با حذف دسته بندی تمامی اپراتور ها و محتوای مربوط به ان حذف خواهند شد ، دقت کنید
                        </h4>
                    </div>
                    <div class="text-center mt-3" id="add-post">
                        <button type="submit" class="btn btn-danger col-12">
                            متوجه ام ، حذف دسته بندی
                        </button>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menus.js' %}"></script>
    <script>
        // ----------------- Modal Category Add -----------------
        let btnsShowModal = document.querySelector("#add-category");
        let btnsCloseModal = document.querySelector(".close-modal-add-category");
        let contentModals = document.querySelector(".add-category-modal");

        btnsShowModal.addEventListener("click", () => {
            contentModals.classList.add("active");
        });

        btnsCloseModal.addEventListener("click", () => {
            contentModals.classList.remove("active");
        });
        contentModals.addEventListener("click", (e) => {
            if (e.target.className === "inner-modal")
                contentModals.classList.remove("active");
        });

        // ----------------- Modal Category Delete -----------------
        let btnsShowModal_b = document.querySelector("#delete-category");
        let btnsCloseModal_b = document.querySelector(".close-modal-delete-category");
        let contentModals_b = document.querySelector(".delete-category-modal");

        btnsShowModal_b.addEventListener("click", () => {
            contentModals_b.classList.add("active");
        });

        btnsCloseModal_b.addEventListener("click", () => {
            contentModals_b.classList.remove("active");
        });
        contentModals_b.addEventListener("click", (e) => {
            if (e.target.className === "inner-modal")
                contentModals_b.classList.remove("active");
        });
    </script>
{% endblock %}