src/apps/operation/urls.py
from django.urls import path
from .views import test, recovery, counseling, routine


app_name = 'operation'

urlpatterns = [
    path('tests/', test.TestsView.as_view(), name='tests_list'),
    path('tests/add/', test.AddTestView.as_view(), name='add_test'),
    path('tests/<int:pk>/details/', test.TestDetailsView.as_view(), name='test_details'),
    path('test/<int:pk>/answer/', test.UpdateTestView.as_view(), name='answer_test'),

    path('recovery/list/', recovery.RecoveryProcessesView.as_view(), name='recoveries_list'),
    path('recovery/add/', recovery.AddRecoveryProcessView.as_view(), name='add_recovery_process'),
    path('recovery/<int:pk>/delete/', recovery.DeleteRecoveryProcessView.as_view(), name='delete_recovery_process'),
    path('recovery/<int:pk>/details/', recovery.RecoveryProcessDetailsView.as_view(), name='recovery_process_details'),
    path('recovery/add-image/', recovery.AddRecoveryProcessImageView.as_view(), name='add_recovery_process_image'),
    path('recovery/delete-image/', recovery.DeleteRecoveryProcessImageView.as_view(), name='delete_recovery_process_image'),

    path('counseling/list/', counseling.CounselingsListView.as_view(), name='counselings_list'),
    path('counseling/add/', counseling.AddCounselingView.as_view(), name='add_counseling'),
    path('counseling/<int:pk>/answer/', counseling.ToggleCounselingAnswerView.as_view(), name='counseling_answer'),

    path('routine/list/', routine.RoutinesView.as_view(), name='routines_list'),
    path('routine/add/', routine.AddRoutineView.as_view(), name='add_routine'),
    path('routine/<int:pk>/delete/', routine.DeleteRoutineView.as_view(), name='delete_routine'),
    path('routine/<int:pk>/details/', routine.RoutineDetailsView.as_view(), name='routine_details'),
    path('routine/<int:pk>/answer/', routine.AnswerRoutineView.as_view(), name='answer_routine'),
]

src/config/urls.py
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls', namespace='public')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('service/', include('apps.service.urls', namespace='service')),
    path('shop/', include('apps.shop.urls', namespace='shop')),
    path('program/', include('apps.program.urls', namespace='program')),
    path('operation/', include('apps.operation.urls', namespace='operation')),
    path('communication/', include('apps.communication.urls', namespace='communication')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler403 = 'apps.public.views.err_403_handler'
# handler404 = 'apps.public.views.err_404_handler'
# handler500 = 'apps.public.views.err_500_handler'


# Rename site header & title & index_title
admin.site.site_header = _("Site Management")
admin.site.index_title = _("Management Panel")
admin.site.site_title = _("Vala Clinic")

src/apps/operation/forms.py
from django import forms
from . import models


# AnswerTest form
class AnswerTestForm(forms.ModelForm):
    class Meta:
        model = models.Test
        fields = ('user', 'answer')


# AddCounseling form
class AddCounselingForm(forms.ModelForm):
    class Meta:
        model = models.Counseling
        fields = ('user', 'title', 'description', 'file')


# AddSkinRoutine form
class AddSkinRoutineForm(forms.ModelForm):
    class Meta:
        model = models.SkinRoutine
        exclude = ('answer', 'is_active')


# AnswerRoutine form
class AnswerRoutineForm(forms.ModelForm):
    class Meta:
        model = models.SkinRoutine
        fields = ('user', 'answer')

src/apps/operation/views/counseling.py
from django.views.generic import View, TemplateView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q

from apps.account.mixins import AccessRequiredMixin
from apps.account.enums import UserAccessEnum
from apps.core.utils import remove_first_char
from ..models import Counseling
from .. import forms


# Render CounselingsList view
class CounselingsListView(LoginRequiredMixin, ListView):
    template_name = 'operation/counselings/list.html'
    model = Counseling

    def get_template_names(self):
        if self.request.user.has_admin_access:
            return 'operation/counselings/admin/list.html'
        return super().get_template_names()

    def filter(self, objects):
        q = self.request.GET.get('q')
        if q:
            q = remove_first_char(q)
            objects = objects.filter(Q(user__phone_number__contains=q) | Q(user__last_name__icontains=q))

        return objects

    def get_queryset(self):
        if self.request.user.has_admin_access:
            objects = Counseling.objects.filter(is_active=True)
            return self.filter(objects)

        return Counseling.objects.filter(is_active=True, user=self.request.user)


# Add Counseling view
class AddCounselingView(LoginRequiredMixin, CreateView):
    template_name = 'operation/counselings/list.html'
    model = Counseling
    form_class = forms.AddCounselingForm
    success_url = reverse_lazy('operation:counselings_list')

    def form_valid(self, form):
        messages.success(self.request, _('Counseling request registered successfully'))
        return super().form_valid(form)


# Toggle Counseling answer view
class ToggleCounselingAnswerView(AccessRequiredMixin, View):
    roles = [UserAccessEnum.ADMIN]

    def get(self, request, pk):
        try:
            obj = Counseling.objects.get(pk=pk)
            obj.is_answered = not obj.is_answered
            obj.save()
        except Counseling.DoesNotExist:
            return JsonResponse({'response': 'error'}, status=404)

        return JsonResponse({'response': 'answered'}, status=200)

src/apps/operation/views/recovery.py
from django.views.generic import View, TemplateView, CreateView, DetailView
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.urls import reverse_lazy
from django.contrib import messages

from ..models import RecoveryProcess, RecoveryProcessImage


# Render RecoveryProcesses view
class RecoveryProcessesView(LoginRequiredMixin, TemplateView):
    template_name = 'operation/recovery/processes-list.html'

    def get_context_data(self, **kwargs):
        contexts = super().get_context_data(**kwargs)
        processes = RecoveryProcess.objects.filter(is_active=True, user=self.request.user)
        contexts['processes'] = processes

        return contexts


# Add RecoveryProcess view
class AddRecoveryProcessView(LoginRequiredMixin, CreateView):
    template_name = 'operation/recovery/processes-list.html'
    success_url = reverse_lazy('operation:recoveries_list')
    model = RecoveryProcess
    fields = ('user', 'title')

    def form_valid(self, form):
        messages.success(self.request, _('Recovery process added successfully'))
        return super().form_valid(form)


# Delete RecoveryProcess view
class DeleteRecoveryProcessView(LoginRequiredMixin, View):

    def get(self, request, pk):
        obj = get_object_or_404(RecoveryProcess, pk=pk)
        obj.is_active = False
        obj.save()

        messages.success(request, _('Recovery process deleted successfully'))
        return redirect('operation:recoveries_list')


# Render RecoveryProcessDetails view
class RecoveryProcessDetailsView(LoginRequiredMixin, DetailView):
    template_name = 'operation/recovery/process-details.html'
    model = RecoveryProcess


# Add RecoveryProcessImage view
class AddRecoveryProcessImageView(LoginRequiredMixin, CreateView):
    template_name = 'operation/recovery/process-details.html'
    model = RecoveryProcessImage
    fields = ('recovery_process', 'image')

    def form_valid(self, form):
        messages.success(self.request, _('Image added successfully'))
        return super().form_valid(form)


# Delete RecoveryProcessImage view
class DeleteRecoveryProcessImageView(LoginRequiredMixin, View):

    def post(self, request):
        data = request.POST.copy()
        obj = get_object_or_404(RecoveryProcessImage, pk=data.get('pk'))

        parent_pk = obj.recovery_process.pk
        obj.delete()

        messages.success(self.request, _('Image deleted successfully'))
        return redirect('operation:recovery_process_details', parent_pk)

src/apps/operation/views/routine.py
from django.views.generic import View, UpdateView, CreateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q

from apps.account.mixins import AccessRequiredMixin
from apps.account.enums import UserAccessEnum
from apps.core.utils import remove_first_char
from ..models import SkinRoutine
from .. import forms


# Render Routines view
class RoutinesView(LoginRequiredMixin, ListView):
    template_name = 'operation/routines/routines.html'
    model = SkinRoutine

    def get_template_names(self):
        if self.request.user.has_admin_access:
            return 'operation/routines/admin/routines.html'
        return super().get_template_names()

    def filter(self, objects):
        q = self.request.GET.get('q')
        if q:
            q = remove_first_char(q)
            objects = objects.filter(Q(user__phone_number__contains=q) | Q(user__last_name__icontains=q))

        return objects

    def get_queryset(self):
        if self.request.user.has_admin_access:
            objects = SkinRoutine.objects.filter(is_active=True)
            return self.filter(objects)

        return SkinRoutine.objects.filter(is_active=True, user=self.request.user)


# Render RoutineDetails view
class RoutineDetailsView(LoginRequiredMixin, DetailView):
    template_name = 'operation/routines/details.html'
    model = SkinRoutine


# Add Routine view
class AddRoutineView(LoginRequiredMixin, CreateView):
    template_name = 'operation/routines/add.html'
    model = SkinRoutine
    form_class = forms.AddSkinRoutineForm
    success_url = reverse_lazy('operation:routines_list')

    def form_valid(self, form):
        messages.success(self.request, _('Routine registered successfully'))
        return super().form_valid(form)


# Answer Routine view
class AnswerRoutineView(AccessRequiredMixin, UpdateView):
    template_name = 'operation/routines/details.html'
    model = SkinRoutine
    form_class = forms.AnswerRoutineForm
    roles = [UserAccessEnum.ADMIN]

    def get_success_url(self):
        return reverse('operation:routine_details', args=[self.object.pk])

    def form_valid(self, form):
        messages.success(self.request, _('Answer successfully added'))
        return super().form_valid(form)


# Delete Routine view
class DeleteRoutineView(AccessRequiredMixin, View):
    roles = [UserAccessEnum.ADMIN]

    def get(self, request, pk):
        try:
            obj = SkinRoutine.objects.get(pk=pk)
            obj.is_active = False
            obj.save()
        except SkinRoutine.DoesNotExist:
            messages.error(request, _('There is an issue'))
            return redirect('operation:routines_list')

        messages.success(request, _('Routine successfully deleted'))
        return redirect('operation:routines_list')

src/apps/operation/views/test.py
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q

from apps.account.mixins import AccessRequiredMixin
from apps.account.enums import UserAccessEnum
from apps.core.utils import remove_first_char
from ..models import Test
from .. import forms


# Render Tests view
class TestsView(LoginRequiredMixin, ListView):
    template_name = 'operation/tests/tests.html'
    model = Test
    context_object_name = 'tests'

    def filter(self, objects):
        q = self.request.GET.get('q')
        if q:
            q = remove_first_char(q)
            objects = objects.filter(Q(user__phone_number__contains=q) | Q(user__last_name__icontains=q))

        return objects

    def get_queryset(self):
        if self.request.user.has_admin_access:
            objects = Test.objects.filter(is_active=True)
            return self.filter(objects)

        return Test.objects.filter(is_active=True, user=self.request.user)


# Render TestDetails view
class TestDetailsView(LoginRequiredMixin, DetailView):
    template_name = 'operation/tests/test-details.html'
    model = Test


# Update Test view
class UpdateTestView(AccessRequiredMixin, UpdateView):
    template_name = 'operation/tests/test-details.html'
    model = Test
    form_class = forms.AnswerTestForm
    roles = [UserAccessEnum.ADMIN]

    def get_success_url(self):
        return reverse('operation:test_details', args=[self.object.pk])

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.status = obj.State.ANSWERED
        obj.save()

        # TODO: Send sms for user to see the answer
        messages.success(self.request, _('Answer successfully added'))
        return super().form_valid(form)


# Add Test view
class AddTestView(LoginRequiredMixin, CreateView):
    template_name = 'operation/tests/tests.html'
    success_url = reverse_lazy('operation:tests_list')
    model = Test
    fields = ('user', 'title', 'text', 'file')

    def form_valid(self, form):
        obj = form.save(commit=False)

        # Check if user saved more than unanswered test
        test_counts = Test.objects.filter(is_active=True, user=obj.user, status='await').count()
        if test_counts >= 3:
            messages.error(self.request, _('You cannot register more than 3 unanswered test'))
            return redirect('operation:tests_list')

        obj.save()

        messages.success(self.request, _('Test added successfully'))
        return super().form_valid(form)

src/apps/operation/templates/operation/counselings/list.html
{% extends 'base-template.html' %}
{% load static %}


{% block title %}والا | مشاوره ها{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/counselings.css' %}">
{% endblock %}

{% block content %}
    {% include 'menus.html' %}

    <!-- Start Request counseling modal -->
    <div class="modal fade" tabindex="-1" id="requestCounselingModal" aria-labelledby="requestCounselingModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <form method="POST" action="{% url 'operation:add_counseling' %}" enctype="multipart/form-data"
                  class="modal-content text-white border-white border-1 rounded-3" style="background-color: #2d2c2c;">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title fw-semibold h4">درخواست مشاوره جدید</h5>
                    <i role="button" class="bi bi-x-lg" data-bs-dismiss="modal" aria-label="Close"></i>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="user" value="{{ user.pk }}">
                    <div class="d-flex flex-column form-group">
                        <label class="form-label" style="font-size: 16px;">
                            عنوان مشاوره
                            <input type="text" name="title" class="form form-control mt-1" style="background-color: #e1e1e1;" required>
                        </label>
                    </div>
                    <div class="d-flex flex-column form-group">
                        <label class="form-label" style="font-size: 16px;">
                            متن درخواست
                            <textarea name="description" class="form form-control mt-1" cols="5" style="background-color: #e1e1e1;" required></textarea>
                        </label>
                    </div>
                    <div class="d-flex flex-column form-group">
                        <label class="form-label" style="font-size: 16px;">
                            فایل پیوست(اختیاری)
                            <input type="file" name="file" accept="application/pdf, image/*" class="form form-control mt-1" style="background-color: #e1e1e1;">
                        </label>
                    </div>
                </div>
                <div class="modal-footer border-top-0">
                    <button type="button" class="btn btn-danger fw-semibold rounded-3 px-3" data-bs-dismiss="modal" aria-label="Close">بستن</button>
                    <button type="submit" class="btn btn-light fw-semibold rounded-3 px-3">ارسال</button>
                </div>
            </form>
        </div>
    </div>
    <!-- .End Request counseling modal -->

    <div class="container-fluid col-md-11 bg">
        <div class="d-flex justify-content-between gap-3 px-3 pt-4 pb-2">
            <div></div>
            <div>
                <button class="btn btn-light" data-bs-toggle="modal" data-bs-target="#requestCounselingModal">
                    درخواست مشاوره
                </button>
            </div>
        </div>

        <main class="main pb-5">
            <section class="content-items" id="container-tickets">

                {% for obj in object_list %}
                    <div class="col-12 col-md-6 p-1">
                        <div class="item-ticket position-relative">
                            <div class="counseling-state text-white">
                                {% if obj.is_answered %}
                                    <span class="bg-success p-2 state">پایان</span>
                                {% else %}
                                    <span class="bg-danger p-2 state">بی پاسخ</span>
                                {% endif %}
                            </div>

                            <div class="title d-flex justify-content-between align-items-center mb-2">
                                <span>شما</span>
                            </div>
                            <div class="des-1 mt-3">
                                <span class="fw-semibold">عنوان:</span> {{ obj.title }}
                            </div>
                            <div class="d-flex flex-column mt-3">
                                <span class="text-white">متن درخواست</span>
                                <div class="des-2">
                                    <span style="font-size: 16px;">{{ obj.description }}</span>
                                </div>
                            </div>
                            <div class="d-flex mt-2">
                                <a href="{{ obj.get_file_url }}" target="_self" class="btn btn-success">
                                    فایل پیوست
                                </a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="container-not-found-base p-4 fs-4">
                        <p>مشاوره‌ ای ثبت نشده</p>
                    </div>
                {% endfor %}

            </section>
        </main>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menus.js' %}"></script>
{% endblock %}