src/apps/communication/urls.py
from django.urls import path
from . import views


app_name = 'communication'

urlpatterns = [
    path('tickets/', views.TicketsListView.as_view(), name='tickets_list'),
    path('tickets/add/', views.AddTicketView.as_view(), name='add_ticket'),
    path('tickets/all/', views.AdminTicketsListView.as_view(), name='all_tickets'),

    path('chat/list/', views.ChatListView.as_view(), name='chats_list'),
    path('chat/session/<int:pk>/', views.ChatRoomView.as_view(), name='chat_room'),
    path('chat/create/', views.CreateChatRoomView.as_view(), name='create_chat'),
    path('chat/session/send-message/', views.SendMessageView.as_view(), name='send_chat_message'),
]

src/config/urls.py
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls', namespace='public')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('service/', include('apps.service.urls', namespace='service')),
    path('shop/', include('apps.shop.urls', namespace='shop')),
    path('program/', include('apps.program.urls', namespace='program')),
    path('operation/', include('apps.operation.urls', namespace='operation')),
    path('communication/', include('apps.communication.urls', namespace='communication')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler403 = 'apps.public.views.err_403_handler'
# handler404 = 'apps.public.views.err_404_handler'
# handler500 = 'apps.public.views.err_500_handler'


# Rename site header & title & index_title
admin.site.site_header = _("Site Management")
admin.site.index_title = _("Management Panel")
admin.site.site_title = _("Vala Clinic")

src/apps/communication/models.py
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from django.db import models

from apps.core.models import BaseModel
from .enums import TicketStatusChoices

User = get_user_model()


# Tickets model
class Ticket(BaseModel):
    Status = TicketStatusChoices

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('User'), related_name='tickets')
    title = models.CharField(_('Title'), max_length=128, null=True, blank=True)
    text = models.TextField(_('Ticket text'))
    status = models.CharField(_('Status'), max_length=64, choices=Status.choices, default=Status.OPEN)
    answer = models.TextField(_('Admin answer'), null=True, blank=True)
    is_active = models.BooleanField(_('Active'), default=True)

    class Meta:
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')
        ordering = ('-id',)

    def __str__(self):
        return f'{self.user} - {self.title}'


# ChatRooms model
class ChatRoom(BaseModel):
    participants = models.ManyToManyField(User, related_name='chat_rooms', verbose_name=_('Participants'))
    title = models.CharField(_('Title'), max_length=255, default=_('No title'))
    is_active = models.BooleanField(_('Active'), default=True)

    class Meta:
        verbose_name = _('Chat room')
        verbose_name_plural = _('Chat rooms')
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('communication:chat_room', args=[self.pk])

    def get_messages(self):
        return self.messages.all()

    def get_unread_messages(self):
        return self.messages.filter(is_read=False)

    def get_participant(self):
        return self.participants.first()

    def get_date_created(self):
        return self.created_at.strftime('%Y-%m-%d')


# ChatMessages model
class Message(BaseModel):
    chat_room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name='messages', verbose_name=_('Chat room'))
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='chat_messages', null=True, blank=True, verbose_name=_('Sender'))
    content = models.TextField(_('Content'))
    is_read = models.BooleanField(_('Is read'), default=False)

    class Meta:
        verbose_name = _('Chat message')
        verbose_name_plural = _('Chat messages')
        ordering = ('created_at',)

    def __str__(self):
        return f'{self.chat_room} - {self.sender} - {self.created_at}'

src/apps/communication/forms.py
from django.core.exceptions import ValidationError
from django import forms
from .models import ChatRoom, Message


# Create Chat Message form
class CreateChatMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('chat_room', 'sender', 'content')

    def clean(self):
        room = self.cleaned_data.get('chat_room')
        sender = self.cleaned_data.get('sender')

        try:
            chat_room = ChatRoom.objects.get(pk=room.pk)
            if not sender.has_admin_access and not chat_room.participants.filter(pk=sender.pk).exists():
                raise ValidationError('An error has occurred', code='403_FORBIDDEN')
        except (ChatRoom.DoesNotExist, AttributeError):
            raise ValidationError('An error has occurred', code='403_FORBIDDEN')

        return self.cleaned_data

src/apps/communication/views.py
from django.views.generic import TemplateView, CreateView, View, ListView, DetailView
from django.shortcuts import get_object_or_404, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q

from apps.account.mixins import AccessRequiredMixin, UserAccessEnum
from apps.core.utils import remove_first_char
from .models import Ticket, ChatRoom, Message
from . import forms


# Render TicketsListView
class TicketsListView(LoginRequiredMixin, TemplateView):
    template_name = 'communication/tickets/tickets.html'

    def get_context_data(self, **kwargs):
        contexts = super().get_context_data(**kwargs)

        tickets = Ticket.objects.filter(user=self.request.user, is_active=True)
        contexts['tickets'] = tickets

        return contexts


# Render AdminTicketsListView
class AdminTicketsListView(AccessRequiredMixin, TemplateView):
    template_name = 'communication/tickets/tickets-admin.html'
    roles = [UserAccessEnum.ADMIN]

    def get_context_data(self, **kwargs):
        contexts = super().get_context_data(**kwargs)

        tickets = Ticket.objects.filter(is_active=True)
        contexts['tickets'] = tickets

        return contexts

    def post(self, request):
        data = request.POST.copy()
        ticket = get_object_or_404(Ticket, id=data.get('id'))

        ticket.answer = data.get('answer')
        ticket.save()

        messages.success(request, _('Answer successfully added'))
        return redirect('communication:all_tickets')


# Add Ticket view
class AddTicketView(LoginRequiredMixin, CreateView):
    template_name = 'communication/tickets/tickets.html'
    model = Ticket
    fields = ('user', 'title', 'text')
    success_url = reverse_lazy('communication:tickets_list')

    def form_valid(self, form):
        messages.success(self.request, _('Ticket registered successfully'))
        return super().form_valid(form)


# Render ChatList view
class ChatListView(LoginRequiredMixin, ListView):
    template_name = 'communication/chat/chat-list.html'
    model = ChatRoom

    def get_template_names(self):
        if self.request.user.has_admin_access:
            return 'communication/chat/admin/chat-list.html'
        return super().get_template_names()

    def filter(self, objects):
        q = self.request.GET.get('q')
        try:
            q = remove_first_char(q)
            objects = objects.filter(Q(id=q) | Q(participants__phone_number__contains=q))
        except (ValueError, AttributeError, TypeError):
            pass

        return objects

    def get_queryset(self):
        if self.request.user.has_admin_access:
            objects = ChatRoom.objects.filter(is_active=True)
            return self.filter(objects)

        objects = ChatRoom.objects.filter(is_active=True, participants=self.request.user)
        return self.filter(objects)


# Render ChatRoom view
class ChatRoomView(LoginRequiredMixin, DetailView):
    template_name = 'communication/chat/chat-room.html'
    model = ChatRoom

    def dispatch(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        chat_room = get_object_or_404(ChatRoom, pk=pk)
        chat_room.messages.update(is_read=True)

        return super().dispatch(request, *args, **kwargs)
    
    def get_template_names(self):
        if self.request.user.has_admin_access:
            return 'communication/chat/admin/chat-room.html'
        return super().get_template_names()


# Create ChatRoom view
class CreateChatRoomView(LoginRequiredMixin, View):

    def get(self, request):
        # Check if user created more than 1 chat rooms
        if ChatRoom.objects.filter(is_active=True, participants=request.user).count() >= 1:
            messages.error(request, _('You cannot create more than 1 active chat room'))
            return redirect('communication:chats_list')

        # Create chatroom and set the current user as participant
        obj = ChatRoom.objects.create()
        obj.participants.add(request.user)
        obj.save()

        return redirect('communication:chat_room', obj.pk)


# SendMessage view
class SendMessageView(LoginRequiredMixin, CreateView):
    template_name = 'communication/chat/chat-room.html'
    model = Message
    form_class = forms.CreateChatMessageForm

    def get_success_url(self):
        pk = self.request.POST.get('chat_room')
        return reverse('communication:chat_room', args=[pk])

    def form_invalid(self, form):
        http_referer = self.request.META.get('HTTP_REFERER')
        return redirect(http_referer)

src/apps/communication/templates/communication/chat/chat-list.html
{% extends 'base-template.html' %}
{% load static %}


{% block title %}والا | چت ها{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/chat-list.css' %}">
{% endblock %}

{% block content %}
    {% include 'menus.html' %}

    <div class="container-fluid col-md-11 bg">
        <div class="d-flex justify-content-between gap-3 px-3 pt-4 pb-2">
            <div></div>
            <div>
                <a href="{% url 'communication:create_chat' %}" class="btn btn-light fw-semibold">
                    + شروع چت جدید
                </a>
            </div>
        </div>

        <main class="main pb-5">
            <section class="p-md-5 p-3 row" id="container-tickets">

                {% for chat in object_list %}
                    <div class="col-md-6 col-12 mb-4 test-card">
                        <div class="d-flex flex-column">
                            <div class="d-flex flex-column position-relative p-3 test-card-header">
                                <h4 class="convert-digits" style="font-weight: 600;">چت شماره {{ forloop.counter }}</h4>
                            </div>

                            <div class="d-flex justify-content-between align-items-center gap-2 text-white px-3 pt-3 pb-2 test-card-body">
                                <div class="d-flex gap-md-5 gap-4">
                                    <div class="d-flex flex-column fw-semibold">
                                        <span>کاربر:</span>
                                        <span class="convert-digits">{{ chat.get_participant }}</span>
                                    </div>
                                    <div class="d-flex flex-column fw-semibold">
                                        <span>شناسه:</span>
                                        <span class="convert-digits">{{ chat.id }}</span>
                                    </div>
                                    <div class="d-flex flex-column fw-semibold">
                                        <span>تاریخ:</span>
                                        <span class="datetime-convert">{{ chat.get_date_created }}</span>
                                    </div>
                                </div>

                                <div class="d-flex flex-wrap gap-2">
                                    <a href="{{ chat.get_absolute_url }}" class="btn btn-sm btn-success fw-semibold">مشاهده</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="container-not-found-base p-4 fs-4">
                        <p>چت روم ساخته نشده</p>
                    </div>
                {% endfor %}

            </section>
        </main>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/menus.js' %}"></script>
{% endblock %}

src/apps/communication/templates/communication/chat/chat-room.html
{% extends 'base-template.html' %}
{% load static %}


{% block title %}چت روم - {{ object.title }}{% endblock %}

{% block styles %}
    <meta http-equiv="refresh" content="60">
    <link rel="stylesheet" href="{% static 'styles/chatroom.css' %}">
{% endblock %}

{% block body_class %}bg{% endblock %}

{% block content %}
    {% include 'menus.html' %}

    <div class="container-fluid col-md-11">
        <main class="main" style="padding-bottom: 140px;">
            <div class="d-flex justify-content-between align-items-center p-2">
                <div></div>
                <div class="d-flex position-fixed" style="top: 8px; left: 8px;">
                    <a href="{% url 'communication:chats_list' %}" class="btn btn-danger">
                        بازگشت
                    </a>
                </div>
            </div>

            <section class="category">
                <!-- Start user messages -->
                {% for message in object.get_messages %}

                    {% if message.sender == user %}
                        <div class="messege-content answer">
                            <div class="col-12 col-md-6 p-1">
                                <div class="item-message">
                                    <div class="col-10 col-lg-11 p-2">
                                        <div class="fw-semibold p-1" style="font-size: 18px;">
                                            <span class="text-success">شما</span>
                                        </div>
                                        <div class="content-message">
                                            {{ message.content }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="messege-content send-user">
                            <div class="col-12 col-md-6">
                                <div class="item-message">
                                    <div class="col-10 col-lg-11 p-2">
                                        <div class="fw-semibold p-1" style="font-size: 18px;">
                                            <span class="text-danger">ادمین والا</span>
                                        </div>
                                        <div class="content-message">
                                            {{ message.content }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <!-- .End user messages -->


                <!-- Start input/send message -->
                <form method="POST" action="{% url 'communication:send_chat_message' %}" class="input-send-messageee">
                    {% csrf_token %}
                    <input type="hidden" name="chat_room" value="{{ object.pk }}">
                    <input type="hidden" name="sender" value="{{ user.pk }}">

                    <div class="col-12 answer-content">
                        <div class="col-9 col-lg-11 p-1 dddd">
                            <input type="text" name="content" placeholder="تایپ کنید" class="px-2" required>
                        </div>
                        <div class="col-2 col-lg-1 sss">
                           <button type="submit" class="btn btn-light px-3">
                                ارسال
                           </button>
                        </div>
                    </div>
                </form>
                <!-- .End input/send message -->

            </section>

        </main>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'js/menus.js' %}"></script>
{% endblock %}