src/apps/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='account:login'), name='logout'),

    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/verify/', views.VerifyPhoneNumberView.as_view(), name='verify_phone'),
    path('register/questions/', views.CompleteProfileView.as_view(), name='complete_profile'),
    path('register/send-code/', views.SendCodeView.as_view(), name='send_verify_code'),
    path('register/complete/', views.CompleteRegisterView.as_view(), name='complete_register'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/details/', views.ProfileDetailView.as_view(), name='profile_details'),
    path('profile/update/', views.UpdateProfileView.as_view(), name='profile_update'),

    path('password/edit/', views.EditUserPassView.as_view(), name='edit_password'),
    path('password/reset/', views.GetPhoneNumberView.as_view(), name='get_phone_number'),
    path('password/reset/verify/', views.ResetPasswordVerifyView.as_view(), name='reset_password_verify'),
    path('password/reset/confirm/', views.ResetPasswordConfirmView.as_view(), name='reset_password_confirm'),

    path('users/list/', views.UsersListView.as_view(), name='users_list'),
]

src/apps/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'apps.dashboard'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

src/apps/notification/urls.py
from django.urls import path
from . import views

app_name = 'notification'
urlpatterns = [
    # dashboard
    path('dashboard/user/add', views.NotificationUserAdd.as_view(), name='notification_user__add'),
    path('dashboard/user/<int:notification_id>/delete', views.NotificationUserDelete.as_view(), name='notification_user__delete'),
    path('dashboard/user/detail/<int:notification_id>', views.NotificationUserDetail.as_view(),
         name='notification_user__detail'),
    path('dashboard/personal/list', views.NotificationUserPersonalList.as_view(), name='notification_personal__list'),
    path('dashboard/user/list', views.NotificationUserList.as_view(), name='notification_user__list'),
]

src/apps/service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    # Operator Category
    path('operator/category/add', views.OperatorCategoryAddView.as_view(), name='operator_category__add'),
    path('operator/category/list', views.OperatorCategoryListView.as_view(), name='operator_category__list'),
    path('operator/category/delete/<int:category_id>', views.OperatorCategoryDeleteView.as_view(),
         name='operator_category__delete'),
    path('operator/category/detail/<int:category_id>', views.OperatorCategoryDetailView.as_view(),
         name='operator_category__detail'),
    # Operator
    path('operator/add', views.OperatorAddView.as_view(), name='operator__add'),
    path('operator/delete/<int:operator_id>', views.OperatorDeleteView.as_view(), name='operator__delete'),
    path('operator/detail/<int:operator_id>', views.OperatorDetailView.as_view(), name='operator__detail'),
    # Operator WorkSample
    path('operator/worksample/add', views.OperatorWorkSampleAddView.as_view(), name='operator_worksample__add'),
    path('operator/worksample/delete/<int:work_sample_id>', views.OperatorWorkSampleDeleteView.as_view(),
         name='operator_worksample__delete'),
    # Operator Reserve Time
    path('operator/detail/<int:operator_id>/reserve/add', views.OperatorReserveAddView.as_view(),
         name='operator_reserve__add'),
    path('operator/reserve/list', views.OperatorReserveListView.as_view(),
         name='operator_reserve__list'),
]

src/config/urls.py
from django.utils.translation import gettext as _
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.public.urls', namespace='public')),
    path('account/', include('apps.account.urls', namespace='account')),
    path('service/', include('apps.service.urls', namespace='service')),
    path('shop/', include('apps.shop.urls', namespace='shop')),
    path('program/', include('apps.program.urls', namespace='program')),
    path('operation/', include('apps.operation.urls', namespace='operation')),
    path('communication/', include('apps.communication.urls', namespace='communication')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler403 = 'apps.public.views.err_403_handler'
# handler404 = 'apps.public.views.err_404_handler'
# handler500 = 'apps.public.views.err_500_handler'


# Rename site header & title & index_title
admin.site.site_header = _("Site Management")
admin.site.index_title = _("Management Panel")
admin.site.site_title = _("Vala Clinic")

src/apps/account/components/views.py
import json
from django.core.paginator import Paginator
from django.core import serializers
from django.urls import reverse
from django.views.generic import View
from django.http import JsonResponse, Http404
from django.shortcuts import render
from django.db.models import Q, Value, Count
from django.db.models.functions import Concat
from apps.account.auth.mixins import AdminRequiredMixin
from apps.account.models import User
from apps.core.components import BaseComponentView
from apps.cartex.models import Meeting


class ComponentView(BaseComponentView):
    BASE_DIR_TEMPLATE_COMPONENTS = 'account/dashboard/components'


class DashboardUserList(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(DashboardUserList, self).__init__(*args, **kwargs)
        self.template_name = 'user/list.html'

    def pagination(self, objects):
        COUNT_PER_PAGE = 20
        paginator = Paginator(objects, COUNT_PER_PAGE)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return page_obj

    def filter(self, objects):
        request = self.request
        # search
        search_text = request.GET.get('search')
        if search_text:
            objects = objects.annotate(full_name=Concat('first_name', Value(' '), 'last_name'))
            lookup = Q(full_name__icontains=search_text) | Q(phonenumber__icontains=search_text)
            objects = objects.filter(lookup)

        # sort
        sort_by = request.GET.get('sort_by', 'latest')
        if sort_by:
            if sort_by == 'latest':
                objects = objects.order_by('-id')
            elif sort_by == 'oldest':
                objects = objects.order_by('id')
            elif sort_by == 'most-visited':
                objects = objects.annotate(meeting_count=Count('meeting'))
                objects = objects.order_by('-meeting_count')

        return objects

    def get_users(self):
        user = self.request.user
        if user.role == 'super_user':
            return User.normal_user_objects.all()
        elif user.role == 'operator_user':
            return user.get_customers()

    def get_base_context(self):
        users = self.get_users()
        users = self.filter(users)
        pagination = self.pagination(users)
        return {
            'users': pagination.object_list,
            'pagination': pagination
        }


class DashboardUserPersonalDetail(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(DashboardUserPersonalDetail, self).__init__(*args, **kwargs)
        self.template_name = 'user/personal-detail.html'


class DashboardNormalUserDetail(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(DashboardNormalUserDetail, self).__init__(*args, **kwargs)
        self.template_name = 'users/normal/detail.html'

    def get_context_operator_user(self, *args, **kwargs):
        user = kwargs.get('user')
        operator = self.request.user
        context = {
            **kwargs,
            'meetings': operator.get_meetings_with_user(user),
            'all_meetings': Meeting.objects.filter(user=user),
        }
        return context

    def get_context_super_user(self, *args, **kwargs):
        user = kwargs.get('user')
        context = {
            **kwargs,
            'all_meetings': Meeting.objects.filter(user=user),
        }
        return context


class DashboardOperatorUserDetail(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(DashboardOperatorUserDetail, self).__init__(*args, **kwargs)
        self.template_name = 'users/operator/detail.html'

    def get_context_normal_user(self, *args, **kwargs):
        operator = kwargs.get('operator')
        context = {
            **kwargs,
            'meetings': self.request.user.get_meetings_with_operator(operator)
        }
        return context

    def get_context_super_user(self, *args, **kwargs):
        return kwargs


class UserListPartial(AdminRequiredMixin, View):

    def get_users(self):
        return User.objects.exclude(role__in=User.SUPER_USER_ROLES)

    def get_url_search_view(self):
        return reverse('account:user_component_partial__list')

    def get(self, request, **kwargs):
        users = self.get_users()
        page_num = request.GET.get('page', 1)
        pagination = Paginator(users, 15)
        pagination = pagination.get_page(page_num)
        users = pagination.object_list
        context = {
            'users': users,
            'pagination': pagination,
            'url_search_view': self.get_url_search_view()
        }
        return render(request, 'account/dashboard/components/base/user/user-list-partial.html', context)

    def post(self, request):
        data = json.loads(request.body)

        def search(self, objects):
            s = data.get('search')
            if not s:
                return objects
            objects = objects.annotate(full_name=Concat('first_name', Value(' '), 'last_name'))
            lookup = Q(phonenumber__icontains=s) | Q(full_name__icontains=s)
            return objects.filter(lookup)

        # ajax view
        if not request.headers.get('X_REQUESTED_WITH') == 'XMLHttpRequest':
            raise Http404
        users = self.get_users()
        users = search(request, users)
        users_serialized = serializers.serialize('json', users,
                                                 fields=('id', 'first_name', 'last_name', 'phonenumber', 'role'))
        return JsonResponse(users_serialized, safe=False)


class UserNormalListPartial(UserListPartial):

    def get_users(self):
        return User.objects.exclude(role__in=User.ADMIN_ROLES)

    def get_url_search_view(self):
        return reverse('account:user_normal_component_partial__list')

src/apps/cartex/components/views.py
from django.views.generic import View
from django.core.paginator import Paginator
from django.db.models import Q
from apps.core.components import BaseComponentView
from apps.core.utils import add_prefix_phonenum
from apps.cartex import models


class ComponentView(BaseComponentView):
    BASE_DIR_TEMPLATE_COMPONENTS = 'cartex/dashboard/components'


class MeetingDetail(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(MeetingDetail, self).__init__(*args, **kwargs)
        self.template_name = 'cartex/detail.html'

    def get_base_context(self, *args, **kwargs):
        return kwargs


class MeetingList(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(MeetingList, self).__init__(*args, **kwargs)
        self.template_name = 'cartex/list.html'

    def pagination(self, objects):
        COUNT_PER_PAGE = 20
        paginator = Paginator(objects, COUNT_PER_PAGE)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return page_obj

    def filter(self, objects):
        request = self.request
        # search
        search_text = request.GET.get('search')
        if search_text:
            lookup = Q(number_id__icontains=search_text) | Q(areabody__area_code__icontains=search_text)
            # search by phonenumber
            search_text = add_prefix_phonenum(search_text)
            lookup = lookup | Q(
                user__phonenumber=search_text) | Q(operator__phonenumber=search_text)

            objects = objects.filter(lookup)

        # sort
        sort_by = request.GET.get('sort_by', 'latest')
        if sort_by:
            if sort_by == 'latest':
                objects = objects.order_by('-id')
            elif sort_by == 'oldest':
                objects = objects.order_by('id')

        return objects

    def get_meetings(self):
        user = self.request.user
        if user.role == 'super_user':
            return models.Meeting.objects.all()
        return user.get_meetings()

    def get_base_context(self, *args, **kwargs):
        meetings = self.get_meetings()
        meetings = self.filter(meetings)
        pagination = self.pagination(meetings)
        context = {
            'meetings': pagination.object_list,
            'pagination': pagination
        }
        return context

src/apps/dashboard/components/views.py
from django.views.generic import View
from apps.account.models import User
from apps.core.components import BaseComponentView
from apps.cartex.models import Meeting


class ComponentView(BaseComponentView):
    BASE_DIR_TEMPLATE_COMPONENTS = 'dashboard/components'


class DashboardMain(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(DashboardMain, self).__init__(*args, **kwargs)
        self.template_name = 'main.html'

    def get_context_super_user(self):
        operators = User.operator_user_objects.all()
        users = User.normal_user_objects.all()
        meetings = Meeting.objects.all()
        return {
            'operators_count': operators.count(),
            'operators_latest': operators[:8],
            'users_count': users.count(),
            'users_latest': users[:8],
            'meetings': meetings,
        }

    def get_context_operator_user(self):
        user = self.request.user
        meetings = user.get_meetings()
        users = User.normal_user_objects.filter(meeting__operator=user).distinct()
        return {
            'users': users,
            'meetings': meetings,
        }

    def get_context_normal_user(self):
        user = self.request.user
        meetings = user.get_meetings()
        return {
            'meetings': meetings,
        }


class DashboardMenu(ComponentView, View):

    def __init__(self, *args, **kwargs):
        super(DashboardMenu, self).__init__(*args, **kwargs)
        self.template_name = 'menu.html'

src/apps/dashboard/views.py
from django.views.generic import View, TemplateView
from apps.account.auth.mixins import LoginRequiredMixinCustom


class Index(LoginRequiredMixinCustom, TemplateView):
    template_name = 'dashboard/index.html'

src/apps/dashboard/templates/dashboard/components/super_user/menu.html
{% load static %}


<div class="deznav">
    <div class="deznav-scroll">

        <div class="dropdown header-profile">
            <a class="nav-link" href="javascript:void(0);" role="button" data-bs-toggle="dropdown"><img
                    src="{{ user.get_picture_profile_url }}" width="20" alt="">
                <div class="header-info">
                    <span class="font-w400 mb-0"><b>{{ user.get_full_name }}</b></span><small
                        class="text-end font-w400">{{ user.get_raw_phonenumber }}</small>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end">
                <a href="{% url 'account:user_personal__detail' %}" class="dropdown-item ai-icon">
                    <svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18"
                         height="18" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                         stroke-linecap="round" stroke-linejoin="round">
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                        <circle cx="12" cy="7" r="4"></circle>
                    </svg>
                    <span class="ms-2">مشخصات</span></a>
                <a href="{% url 'notification:notification_personal__list' %}"
                   class="dropdown-item ai-icon my-1">
                    <svg id="icon-inbox" xmlns="http://www.w3.org/2000/svg" class="text-success" width="18"
                         height="18" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                         stroke-linecap="round" stroke-linejoin="round">
                        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                        <polyline points="22,6 12,13 2,6"></polyline>
                    </svg>
                    <span class="ms-2">اعلانات</span>
                </a>
                <a href="{% url 'account:logout' %}" class="dropdown-item ai-icon">
                    <svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18"
                         height="18" viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                         stroke-linecap="round" stroke-linejoin="round">
                        <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                        <polyline points="16 17 21 12 16 7"></polyline>
                        <line x1="21" y1="12" x2="9" y2="12"></line>
                    </svg>
                    <span class="ms-2">خروج</span></a>
            </div>
        </div>
        <ul class="metismenu" id="menu">
            <li>
                <a href="{% url 'dashboard:index' %}" class="ai-icon" aria-expanded="false"><i
                        class="flaticon-024-dashboard"></i><span class="nav-text">داشبورد</span></a>
            </li>
            <li>
                <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false"><i
                        class="far fa-users"></i><span class="nav-text">کاربران</span></a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'account:operator__add' %}">افزودن اپراتور</a></li>
                    <li><a href="{% url 'account:user__add' %}">افزودن کاربر </a></li>
                    <li><a href="{% url 'account:operator__list' %}">لیست اپراتور ها</a></li>
                    <li><a href="{% url 'account:user__list' %}">لیست کاربران</a></li>
                </ul>
            </li>
            <li>
                <a class="has-arrow ai-icon" aria-expanded="false"><i
                        class="far fa-user-clock"></i><span class="nav-text">جلسات</span></a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'cartex:meeting__list' %}">لیست جلسات</a></li>
                    <li><a href="#" class="features-update features-update-parent">رزرو جلسه</a></li>
                    <li><a href="#" class="features-update features-update-parent">جلسات رزرو شده</a></li>
                </ul>
            </li>
            <li>
                <a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false"><i
                        class="far fa-bell"></i><span class="nav-text">اعلانات</span></a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'notification:notification_user__add' %}">افزودن اعلان برای کاربر</a></li>
                    <li><a href="{% url 'notification:notification_user__list' %}">لیست اعلانات کاربران </a></li>
                    <li><a href="{% url 'notification:notification_personal__list' %}">اعلانات شخصی</a></li>
                </ul>
            </li>
            <li>
                <a class="has-arrow ai-icon features-update features-update-parent" href="javascript:void()"
                   aria-expanded="false"><i
                        class="far fa-comment-alt"></i><span class="nav-text">نظرات</span></a>
                <ul aria-expanded="false">
                    <li><a href="index.html">افزودن نظر مشتریان</a></li>
                    <li><a href="index-2.html">لیست نظرات مشتریان</a></li>
                </ul>
            </li>
            <li>
                <a class="has-arrow ai-icon features-update features-update-parent" aria-expanded="false"><i
                        class="far fa-magic"></i><span class="nav-text">خدمات</span></a>
                <ul aria-expanded="false">
                    <li><a href="index.html">افزودن خدمات</a></li>
                    <li><a href="index-2.html">لیست خدمات</a></li>
                </ul>
            </li>
            <li>
                <a class="has-arrow ai-icon features-update features-update-parent" aria-expanded="false"><i
                        class="far fa-cog"></i><span class="nav-text">تنظیمات</span></a>
                <ul aria-expanded="false">
                    <li><a href="index.html">تنظیمات اصلی</a></li>
                    <li><a href="index-2.html">بازدید کنندگان</a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'public:index' %}" class="ai-icon features-update features-update-parent"
                   aria-expanded="false"><i
                        class="far fa-comments"></i><span class="nav-text">گفت و گو انلاین</span></a>
            </li>
            <li>
                <a class="has-arrow ai-icon" aria-expanded="false"><i
                        class="far fa-info"></i><span class="nav-text">اطلاعات شخصی</span></a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'account:user_personal__detail' %}">جزئیات</a></li>
                    <li><a href="{% url 'account:user_change_password' %}">تغییر رمز عبور</a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'public:index' %}" class="ai-icon" aria-expanded="false"><i
                        class="far fa-home"></i><span class="nav-text">خانه</span></a>
            </li>
            <li>
                <a href="{% url 'account:logout' %}" class="ai-icon" aria-expanded="false">
                    <i class="far fa-sign-out"></i>
                    <span class="nav-text">خروج</span></a>
            </li>
        </ul>
        <div class="copyright text-center">
            <p>
                <strong>داشبورد مدیریت</strong>
            </p>
            <p class="fs-12">
                ساخته شده با
                <span class="heart"></span>
                توسط
                <a href="https://smartenco.ir"> Smarten Team</a>
            </p>
        </div>
    </div>
</div>